[package]
name = "accesskit_android"
version = "0.1.0"
authors = ["Arnold Loubriat <datatriny@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "AccessKit UI accessibility infrastructure: Android adapter"
categories = ["gui"]
keywords = ["gui", "ui", "accessibility"]
repository = "https://github.com/AccessKit/accesskit"
readme = "README.md"
edition = "2021"

[dependencies]
accesskit = { version = "0.11.0", path = "../../../common" }
accesskit_consumer = { version = "0.15.0", path = "../../../consumer" }
jni = "0.21.1"
lazy_static = "1.4.0"
