[package]
name = "accesskit_winit"
version = "0.22.0"
authors.workspace = true
license = "Apache-2.0"
description = "AccessKit UI accessibility infrastructure: winit adapter"
categories.workspace = true
keywords = ["gui", "ui", "accessibility", "winit"]
repository.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
features = ["winit/rwh_06", "winit/x11", "winit/wayland"]

[features]
default = ["accesskit_unix", "async-io"]
async-io = ["accesskit_unix/async-io"]
tokio = ["accesskit_unix/tokio"]

[dependencies]
accesskit = { version = "0.16.0", path = "../../common" }
winit = { git = "https://github.com/Rust-Windowing/winit", default-features = false, features = ["rwh_06"] }
raw-window-handle = { version = "0.6", features = ["std"] }

[target.'cfg(target_os = "windows")'.dependencies]
accesskit_windows = { version = "0.22.0", path = "../windows" }

[target.'cfg(target_os = "macos")'.dependencies]
accesskit_macos = { version = "0.17.0", path = "../macos" }

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
accesskit_unix = { version = "0.12.0", path = "../unix", optional = true, default-features = false }

[target.'cfg(target_os = "android")'.dependencies]
accesskit_android = { version = "0.1.0", path = "../android", features = ["embedded-dex"] }

[dev-dependencies.winit]
git = "https://github.com/Rust-Windowing/winit"
default-features = false
features = ["rwh_06", "x11", "wayland", "wayland-dlopen", "wayland-csd-adwaita", "android-native-activity"]

[[example]]
name = "simple"

[[example]]
# A custom example target which uses the same `simple.rs` file but for android
name = "simple_android"
path = "examples/simple.rs"
# cdylib is required for cargo-apk
crate-type = ["cdylib"]

[[example]]
name = "mixed_handlers"

[[example]]
# A custom example target which uses the same `mixed_handlers.rs` file but for android
name = "mixed_handlers_android"
path = "examples/mixed_handlers.rs"
# cdylib is required for cargo-apk
crate-type = ["cdylib"]
