[package]
name = "accesskit_unix2"
version = "0.1.0"
authors = ["Matt Campbell <mattcampbell@pobox.com>"]
license = "MIT OR Apache-2.0"
description = "AccessKit UI accessibility infrastructure: new Unix adapter"
categories = ["gui"]
keywords = ["gui", "ui", "accessibility"]
repository = "https://github.com/AccessKit/accesskit"
readme = "README.md"
edition = "2021"

[dependencies]
accesskit = { version = "0.12.2", path = "../../common", features = ["serde"] }
accesskit_consumer = { version = "0.17.0", path = "../../consumer" }
libc = "0.2.149"
once_cell = "1.13.0"
rustix = { version = "0.38.15", features = ["fs", "pipe"] }
sctk = { package = "smithay-client-toolkit", git = "https://github.com/mwcampbell/sctk", branch = "accessibility-protocol", default-features = false, features = ["calloop"] }
serde_json = "1"
wayland-backend = { git = "https://github.com/mwcampbell/wayland-rs.git", branch = "accessibility-protocol", features = ["client_system", "dlopen"] }
wayland-protocols = { git = "https://github.com/mwcampbell/wayland-rs.git", branch = "accessibility-protocol", features = ["client", "staging"] }
